baseurl = "https://yycautomates.github.io/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Calgary Automates"
theme = "universal"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[services]
    # Enable comments by entering your Disqus shortname
    #[services.disqus]
    #    shortname = "devcows"
    # Enable Google Analytics by entering your tracking code
    #[services.googleAnalytics]
    #    id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Resources"
    identifier = "menu.resources"
    url        = "/img/grid.png"
    weight     = 2

[[menu.main]]
    name       = "Examples & Use Cases"
    identifier = "section.examples"
    url        = ""
    weight     = 1
    parent     = "menu.resources"
    post       = 1

[[menu.main]]
    name       = "Success Patterns"
    identifier = "section.patterns"
    url        = ""
    weight     = 2
    parent     = "menu.resources"
    post       = 2

[[menu.main]]
    name       = "Blog"
    identifier = "section.blog"
    url        = ""
    weight     = 3
    parent     = "menu.resources"
    post       = 2

[[menu.main]]
    name       = "GitLab Repository"
    url        = "https://gitlab.com/yycautomates1/community"
    weight     = 1
    parent     = "section.examples"

[[menu.main]]
    name       = "Automation Good Practices"
    url        = "https://redhat-cop.github.io/automation-good-practices/"
    weight     = 1
    parent     = "section.patterns"

[[menu.main]]
    name       = "Articles"
    url        = "/blog/"
    weight     = 1
    parent     = "section.blog"

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitLab"
    url = "https://gitlab.com/yycautomates1/community"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:info@yycautomates.ca"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["automation", "calgary", "yyc", "automates"]
    mainSections = ["blog"]
    defaultDescription = "Posts by our members"

    # Social media
    #facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    #twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    #default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    #enableGoogleMaps = false
    #googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    #latitude = "-12.043333"
    #longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"
    custom_css = ["css/custom.css"]

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    #formspree_action = "https://formspree.io/sample/of/endpoint"
    #contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    #enableRecaptchaInContactForm = false
    #googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Fostering connection and community among technologists and automators in the Calgary area.</p>"
    copyright = "Copyright (c) 2026, Calgary (YYC) Automates ; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Calgary Automates"

    logo = "img/logo.jpg"
    logo_small = "img/logo-small.jpg"
    contact_url = "/contact"
    address = """<p><strong><a href="mailto:info@yycautomates.ca">info@yycautomates.ca</a></strong>
        <br>
        <br>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:contentbasename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">email:  info@yycautomates.ca</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "We break down practical, field-tested strategies that industry leaders are using today to improve adoption, address scale, evangelise & onboard teams, and deploy new use-cases."
    hide_summary = false

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Interested in a particular topic?"
    subtitle = "Find previous presentations, or submit a new topic for discussion."
    link_url = "https://gitlab.com/yycautomates1/community"
    link_text = "Explore Topics"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Technology Partners"
    subtitle = ""

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
